// Auto generated content by `yarn cli update-workspace`
// DO NOT MODIFY THIS FILE MANUALLY
export const packageList = [
  {
    name: '@examples/duplicate-libs',
    version: '1.0.0',
    private: true,
    location: 'examples/duplicate-libs',
  },
  {
    name: '@examples/simple',
    version: '1.0.0',
    private: true,
    location: 'examples/simple',
  },
  {
    name: '@examples/split-chunks',
    version: '1.0.0',
    private: true,
    location: 'examples/split-chunks',
  },
  {
    name: '@johfe/perfsee-bundle-analyzer',
    version: '1.10.0',
    private: false,
    location: 'packages/bundle-analyzer',
  },
  {
    name: '@johfe/perfsee-bundle-report',
    version: '1.12.2',
    private: true,
    location: 'packages/bundle-report',
  },
  {
    name: '@johfe/perfsee-chrome-finder',
    version: '1.10.0',
    private: false,
    location: 'packages/chrome-finder',
  },
  {
    name: '@johfe/perfsee-components',
    version: '1.12.2',
    private: true,
    location: 'packages/components',
  },
  {
    name: '@johfe/perfsee-dls',
    version: '1.3.0',
    private: true,
    location: 'packages/dls',
  },
  {
    name: '@johfe/perfsee-email-templates',
    version: '1.0.0',
    private: true,
    location: 'packages/email-templates',
  },
  {
    name: '@johfe/perfsee-flamechart',
    version: '1.11.0',
    private: false,
    location: 'packages/flamechart',
  },
  {
    name: '@johfe/perfsee-iri',
    version: '1.10.0',
    private: true,
    location: 'packages/iri',
  },
  {
    name: '@johfe/perfsee-jsonr',
    version: '1.12.2',
    private: false,
    location: 'packages/jsonr',
  },
  {
    name: '@johfe/perfsee-lab-report',
    version: '1.12.2',
    private: true,
    location: 'packages/lab-report',
  },
  {
    name: '@johfe/perfsee-ori',
    version: '1.10.0',
    private: true,
    location: 'packages/ori',
  },
  {
    name: '@johfe/perfsee-package-build-stats',
    version: '1.8.4',
    private: false,
    location: 'packages/package-build-stats',
  },
  {
    name: '@johfe/perfsee-package-report',
    version: '1.12.2',
    private: true,
    location: 'packages/package-report',
  },
  {
    name: '@johfe/perfsee-package',
    version: '1.12.2',
    private: false,
    location: 'packages/package',
  },
  {
    name: '@johfe/perfsee-platform-server',
    version: '1.12.2',
    private: true,
    location: 'packages/platform-server',
  },
  {
    name: '@johfe/perfsee-platform',
    version: '1.12.2',
    private: true,
    location: 'packages/platform',
  },
  {
    name: '@johfe/perfsee-schema',
    version: '1.12.0',
    private: true,
    location: 'packages/schema',
  },
  {
    name: '@johfe/perfsee-sdk',
    version: '1.12.2',
    private: false,
    location: 'packages/sdk',
  },
  {
    name: '@johfe/perfsee-server-common',
    version: '1.12.2',
    private: true,
    location: 'packages/server-common',
  },
  {
    name: '@johfe/perfsee-shared',
    version: '1.12.2',
    private: true,
    location: 'packages/shared',
  },
  {
    name: '@johfe/perfsee-source-coverage',
    version: '1.10.0',
    private: true,
    location: 'packages/source-coverage',
  },
  {
    name: '@johfe/perfsee-tracehouse',
    version: '1.10.0',
    private: true,
    location: 'packages/tracehouse',
  },
  {
    name: '@johfe/perfsee-treemap',
    version: '1.12.0',
    private: false,
    location: 'packages/treemap',
  },
  {
    name: '@johfe/perfsee-utils',
    version: '1.10.0',
    private: false,
    location: 'packages/utils',
  },
  {
    name: 'perfsee-vscode',
    version: '1.12.2',
    private: true,
    location: 'packages/vscode-extension',
  },
  {
    name: '@johfe/perfsee-esbuild',
    version: '1.12.2',
    private: false,
    location: 'packages/plugins/esbuild',
  },
  {
    name: '@johfe/perfsee-rollup',
    version: '1.12.2',
    private: false,
    location: 'packages/plugins/rollup',
  },
  {
    name: '@johfe/perfsee-plugin-utils',
    version: '1.12.2',
    private: false,
    location: 'packages/plugins/utils',
  },
  {
    name: '@johfe/perfsee-webpack',
    version: '1.12.2',
    private: false,
    location: 'packages/plugins/webpack',
  },
  {
    name: '@johfe/perfsee-job-runner-bundle',
    version: '1.12.2',
    private: true,
    location: 'packages/runner/bundle',
  },
  {
    name: '@johfe/perfsee-job-runner',
    version: '1.12.2',
    private: true,
    location: 'packages/runner/executor',
  },
  {
    name: '@johfe/perfsee-job-runner-lab',
    version: '1.12.2',
    private: true,
    location: 'packages/runner/lab',
  },
  {
    name: '@johfe/perfsee-job-runner-package',
    version: '1.12.2',
    private: true,
    location: 'packages/runner/package',
  },
  {
    name: '@johfe/perfsee-job-runner-shared',
    version: '1.12.2',
    private: true,
    location: 'packages/runner/shared',
  },
  {
    name: '@johfe/perfsee-job-runner-source',
    version: '1.12.2',
    private: true,
    location: 'packages/runner/source',
  },
] as const

export type PackageName = typeof packageList[number]['name']
